export const STATES = [
  {
    id: 1,
    stateOrProvince: 'Alabama',
    code: 'AL',
    countryCode: 'US',
  },
  {
    id: 2,
    stateOrProvince: 'Alaska',
    code: 'AK',
    countryCode: 'US',
  },
  {
    id: 3,
    stateOrProvince: 'American Samoa',
    code: 'AS',
    countryCode: 'US',
  },
  {
    id: 4,
    stateOrProvince: 'Arizona',
    code: 'AZ',
    countryCode: 'US',
  },
  {
    id: 5,
    stateOrProvince: 'Arkansas',
    code: 'AR',
    countryCode: 'US',
  },
  {
    id: 6,
    stateOrProvince: 'California',
    code: 'CA',
    countryCode: 'US',
  },
  {
    id: 7,
    stateOrProvince: 'Colorado',
    code: 'CO',
    countryCode: 'US',
  },
  {
    id: 8,
    stateOrProvince: 'Connecticut',
    code: 'CT',
    countryCode: 'US',
  },
  {
    id: 9,
    stateOrProvince: 'Delaware',
    code: 'DE',
    countryCode: 'US',
  },
  {
    id: 10,
    stateOrProvince: 'District Of Columbia',
    code: 'DC',
    countryCode: 'US',
  },
  {
    id: 11,
    stateOrProvince: 'Federated States Of Micronesia',
    code: 'FM',
    countryCode: 'US',
  },
  {
    id: 12,
    stateOrProvince: 'Florida',
    code: 'FL',
    countryCode: 'US',
  },
  {
    id: 13,
    stateOrProvince: 'Georgia',
    code: 'GA',
    countryCode: 'US',
  },
  {
    id: 14,
    stateOrProvince: 'Guam Gu',
    code: 'GU',
    countryCode: 'US',
  },
  {
    id: 15,
    stateOrProvince: 'Hawaii',
    code: 'HI',
    countryCode: 'US',
  },
  {
    id: 16,
    stateOrProvince: 'Idaho',
    code: 'ID',
    countryCode: 'US',
  },
  {
    id: 17,
    stateOrProvince: 'Illinois',
    code: 'IL',
    countryCode: 'US',
  },
  {
    id: 18,
    stateOrProvince: 'Indiana',
    code: 'IN',
    countryCode: 'US',
  },
  {
    id: 19,
    stateOrProvince: 'Iowa',
    code: 'IA',
    countryCode: 'US',
  },
  {
    id: 20,
    stateOrProvince: 'Kansas',
    code: 'KS',
    countryCode: 'US',
  },
  {
    id: 21,
    stateOrProvince: 'Kentucky',
    code: 'KY',
    countryCode: 'US',
  },
  {
    id: 22,
    stateOrProvince: 'Louisiana',
    code: 'LA',
    countryCode: 'US',
  },
  {
    id: 23,
    stateOrProvince: 'Maine',
    code: 'ME',
    countryCode: 'US',
  },
  {
    id: 24,
    stateOrProvince: 'Marshall Islands',
    code: 'MH',
    countryCode: 'US',
  },
  {
    id: 25,
    stateOrProvince: 'Maryland',
    code: 'MD',
    countryCode: 'US',
  },
  {
    id: 26,
    stateOrProvince: 'Massachusetts',
    code: 'MA',
    countryCode: 'US',
  },
  {
    id: 27,
    stateOrProvince: 'Michigan',
    code: 'MI',
    countryCode: 'US',
  },
  {
    id: 28,
    stateOrProvince: 'Minnesota',
    code: 'MN',
    countryCode: 'US',
  },
  {
    id: 29,
    stateOrProvince: 'Mississippi',
    code: 'MS',
    countryCode: 'US',
  },
  {
    id: 30,
    stateOrProvince: 'Missouri',
    code: 'MO',
    countryCode: 'US',
  },
  {
    id: 31,
    stateOrProvince: 'Montana',
    code: 'MT',
    countryCode: 'US',
  },
  {
    id: 32,
    stateOrProvince: 'Nebraska',
    code: 'NE',
    countryCode: 'US',
  },
  {
    id: 33,
    stateOrProvince: 'Nevada',
    code: 'NV',
    countryCode: 'US',
  },
  {
    id: 34,
    stateOrProvince: 'New Hampshire',
    code: 'NH',
    countryCode: 'US',
  },
  {
    id: 35,
    stateOrProvince: 'New Jersey',
    code: 'NJ',
    countryCode: 'US',
  },
  {
    id: 36,
    stateOrProvince: 'New Mexico',
    code: 'NM',
    countryCode: 'US',
  },
  {
    id: 37,
    stateOrProvince: 'New York',
    code: 'NY',
    countryCode: 'US',
  },
  {
    id: 38,
    stateOrProvince: 'North Carolina',
    code: 'NC',
    countryCode: 'US',
  },
  {
    id: 39,
    stateOrProvince: 'North Dakota',
    code: 'ND',
    countryCode: 'US',
  },
  {
    id: 40,
    stateOrProvince: 'Northern Mariana Islands',
    code: 'MP',
    countryCode: 'US',
  },
  {
    id: 41,
    stateOrProvince: 'Ohio',
    code: 'OH',
    countryCode: 'US',
  },
  {
    id: 42,
    stateOrProvince: 'Oklahoma',
    code: 'OK',
    countryCode: 'US',
  },
  {
    id: 43,
    stateOrProvince: 'Oregon',
    code: 'OR',
    countryCode: 'US',
  },
  {
    id: 44,
    stateOrProvince: 'Palau',
    code: 'PW',
    countryCode: 'US',
  },
  {
    id: 45,
    stateOrProvince: 'Pennsylvania',
    code: 'PA',
    countryCode: 'US',
  },
  {
    id: 46,
    stateOrProvince: 'Puerto Rico',
    code: 'PR',
    countryCode: 'US',
  },
  {
    id: 47,
    stateOrProvince: 'Rhode Island',
    code: 'RI',
    countryCode: 'US',
  },
  {
    id: 48,
    stateOrProvince: 'South Carolina',
    code: 'SC',
    countryCode: 'US',
  },
  {
    id: 49,
    stateOrProvince: 'South Dakota',
    code: 'SD',
    countryCode: 'US',
  },
  {
    id: 50,
    stateOrProvince: 'Tennessee',
    code: 'TN',
    countryCode: 'US',
  },
  {
    id: 51,
    stateOrProvince: 'Texas',
    code: 'TX',
    countryCode: 'US',
  },
  {
    id: 52,
    stateOrProvince: 'Utah',
    code: 'UT',
    countryCode: 'US',
  },
  {
    id: 53,
    stateOrProvince: 'Vermont',
    code: 'VT',
    countryCode: 'US',
  },
  {
    id: 54,
    stateOrProvince: 'Virgin Islands',
    code: 'VI',
    countryCode: 'US',
  },
  {
    id: 55,
    stateOrProvince: 'Virginia',
    code: 'VA',
    countryCode: 'US',
  },
  {
    id: 56,
    stateOrProvince: 'Washington',
    code: 'WA',
    countryCode: 'US',
  },
  {
    id: 57,
    stateOrProvince: 'West Virginia',
    code: 'WV',
    countryCode: 'US',
  },
  {
    id: 58,
    stateOrProvince: 'Wisconsin',
    code: 'WI',
    countryCode: 'US',
  },
  {
    id: 59,
    stateOrProvince: 'Wyoming',
    code: 'WY',
    countryCode: 'US',
  },
];
